### ISSUE TITLE
Create Database structure.

### ISSUE THREAD

**Issue by sb-github** [sb-github/platform-react#2]
Create database structure for the Platform.

**Comment by sb-github** [comment]
Platform has next [DB scheme](https://github.com/sb-github/platform/wiki/DB-Scheme).

**Comment by sb-github** [comment]
Some changes need to be done.

**Comment by 4rtHurB** [comment]
All needed changes has been done.

**Comment by 4rtHurB** [comment]
All needed changes has been done.
